### ISSUE TITLE
Component always Renders Homepage

### ISSUE THREAD

**Issue by jermsam** [sharethis-github/sharethis-reactjs#10]
Hey.
I've written my component for Facebook share such that when someone clicks on the Facebook button the popup window that comes has this uri in its address bar:
https://www.facebook.com/sharer.php?t=Bates%20College&u=https%3A%2F%2Ftvillage-u.herokuapp.com%2Fdashboard%3FuserId%3D2
I would expect this to render the information within the parameters of this uri. To my surprise, I get the homepage image, and page title plus content rendered instead when I share. I am using v ^1.3.3

I am wondering how this could be fixed.
Thank you.

**Comment by hao-sharethis** [comment]
Hi jermsam, can you double check if the uri is configured as `url` parameter? it would be more helpful if you present us some code, thx.

**Comment by hao-sharethis** [comment]
Hi @jermsam if your issue is fixed, I'll close it now.
