### ISSUE TITLE
BUG: All share buttons disappear? 

### ISSUE THREAD

**Issue by kenzhang98** [sharethis-github/sharethis-reactjs#15]
Hi yall. First of all, great product! Loved it. 

But it seems like there is a bug right now, that none of the buttons are showing up. Even on the live demo page. Is it going to be fixed soon? 

Thanks again.

**Comment by hao-sharethis** [comment]
Hi, thanks for reaching out. i didn't see any issue loading the buttons on the demo page. Can you show some error logs while viewing the buttons on your browser?

**Comment by kenzhang98** [comment]
Huh, strange issue. All the buttons are showing now. Not sure what the issue was. Should've taken a screenshot. 

Thank you still!

**Comment by hao-sharethis** [comment]
np, let me know if see any issue again. good day!
