### ISSUE TITLE
Alternative text for the social imgs

### ISSUE THREAD

**Issue by jermsam** [sharethis-github/sharethis-reactjs#16]
https://platform-cdn.sharethis.com/img/facebook.svg and the like have no alt property description and thus has a negative effect on seo. Is there a way to fix this or provide a property that would enable users to customize this?

**Comment by hao-sharethis** [comment]
Hi Jermsam, appreciate reaching out to us. we've added the <alt> tag, can you try it now?

**Comment by jermsam** [comment]
@hao-sharethis thanks... looks good
