### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by thenickreynolds** [sharethis-github/sharethis-reactjs#21]
It would be great to get typescript support for this library

**Comment by thenickreynolds** [comment]
I've created types for the `InlineShareButtons` which didn't take long - it can be expanded really easily to the rest.

https://gist.github.com/thenickreynolds/a12956503d44656e4496276838a482b9

**Comment by hao-sharethis** [comment]
Hi nick, thanks for your suggestion. I've made an update to include the typescript support. I'm new to typescript so might need your help to validate the result. let me know if that works for you.

**Comment by thenickreynolds** [comment]
Sorry for the delay - it works perfectly for me. I'm only using the `InlineShareButtons` though.
