### ISSUE TITLE
component only renders once in a single page application

### ISSUE THREAD

**Issue by studiotomi** [sharethis-github/sharethis-reactjs#5]
All of the components (`InlineFollowButtons`, `InlineShareButtons`, `InlineReactionButtons`, `StickyShareButtons`) will display properly on a single time.  

```    const _onShareThisLoaded = window.onShareThisLoaded;
    window.onShareThisLoaded = () => {
      if (!config.id) {
        const id = 'sharethis-' + Date.now();
        config.id = id;
      }
      this.buttons.current.id = config.id;
      window.__sharethis__.load('inline-follow-buttons', config);
      if (_onShareThisLoaded) {_onShareThisLoaded();}
    };
```
The onShareThisLoaded function is only called the first time the sharethis library is loaded, so it only displays the component the first time.  If i switch pages, and come back it never displays again.

**Comment by studiotomi** [comment]
I was able to get around this issue by updating code to the componentDidMount sections:

    componentDidMount() {

      // load config
      let config = JSON.parse(JSON.stringify(this.props.config));

      // load sharethis.js
      if (!document.getElementById('sharethis-js')) {
        const script = document.createElement("script");
        script.setAttribute('id', 'sharethis-js');
        script.src = "https://platform-api.sharethis.com/js/sharethis.js" +
          "?product=inline-follow-buttons&source=reactjs";
        script.async = true;
        document.body.appendChild(script);
      }

      // load buttons
      const _onShareThisLoaded = window.onShareThisLoaded;
      window.onShareThisLoaded = () => {
        if (!config.id) {
          const id = 'sharethis-' + Date.now();
          config.id = id;
        }
        this.buttons.current.id = config.id;
        window.__sharethis__.load('inline-follow-buttons', config);
        if (_onShareThisLoaded) {_onShareThisLoaded();}
      };
      // New code.  Could be better.
      if(window.__sharethis__) {
        _onShareThisLoaded = null;
        window.onShareThisLoaded();
      }
      // End new code
    }

**Comment by haosharethis** [comment]
Hi studiotomi, thanks for your post here, we updated the loading method, the issue should be fixed. We also update the babel dependencies to be consistent with the latest one, let me know if it works for your project.

**Comment by haosharethis** [comment]
the latest version is `1.2.0`

**Comment by 3a1b2c3** [comment]
My url changes whats the easiest way yo pass it in?
